"""phishing

Revision ID: 090d21f34246
Revises: 78b834153c19
Create Date: 2025-06-11 13:55:26.649328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090d21f34246'
down_revision: Union[str, None] = '78b834153c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phishing_categories',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_phishing_categories_code'), 'phishing_categories', ['code'], unique=False)
    op.create_table('phishing_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('case_date', sa.Date(), nullable=True),
    sa.Column('reference_url', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['category_code'], ['phishing_categories.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phishing_cases_category_code'), 'phishing_cases', ['category_code'], unique=False)
    op.create_index(op.f('ix_phishing_cases_id'), 'phishing_cases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phishing_cases_id'), table_name='phishing_cases')
    op.drop_index(op.f('ix_phishing_cases_category_code'), table_name='phishing_cases')
    op.drop_table('phishing_cases')
    op.drop_index(op.f('ix_phishing_categories_code'), table_name='phishing_categories')
    op.drop_table('phishing_categories')
    # ### end Alembic commands ###
