"""add starting_message and starters to persona

Revision ID: 37fb7c2cf860
Revises: 449e185ff779
Create Date: 2025-06-16 14:15:28.826238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37fb7c2cf860'
down_revision: Union[str, None] = '449e185ff779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('starting_message', sa.Text(), nullable=True, comment='페르소나의 첫 시작 메시지'))
    op.add_column('personas', sa.Column('conversation_starters', sa.JSON(), nullable=True, comment='대화 시작 선택지 목록 (JSON 배열)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'conversation_starters')
    op.drop_column('personas', 'starting_message')
    # ### end Alembic commands ###
