"""Add applied_phishing_case_id to conversations table

Revision ID: 449e185ff779
Revises: df8a7c8b775d
Create Date: 2025-06-16 09:04:38.797036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '449e185ff779'
down_revision: Union[str, None] = 'df8a7c8b775d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('applied_phishing_case_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_conversations_applied_phishing_case_id'), 'conversations', ['applied_phishing_case_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'phishing_cases', ['applied_phishing_case_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_applied_phishing_case_id'), table_name='conversations')
    op.drop_column('conversations', 'applied_phishing_case_id')
    # ### end Alembic commands ###
