"""Add api_keys table with scopes and expiration

Revision ID: 6c33ae1e739e
Revises: dc62490172ff
Create Date: 2025-06-19 13:41:05.330057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c33ae1e739e'
down_revision: Union[str, None] = 'dc62490172ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False, comment='API 키의 앞 8자리 (식별용)'),
    sa.Column('hashed_key', sa.String(length=255), nullable=False, comment='해싱된 전체 API 키'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='키를 발급한 슈퍼유저 ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='키 용도 설명'),
    sa.Column('scopes', sa.JSON(), nullable=False, comment='이 키가 접근 가능한 권한 범위 목록'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='키 만료일 (NULL이면 무제한)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='키 활성 상태 (False이면 폐기됨)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='마지막 사용일'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
