"""change persona profile_image_url to key

Revision ID: 730f37e3ed08
Revises: 090d21f34246
Create Date: 2025-06-12 06:52:14.802191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730f37e3ed08'
down_revision: Union[str, None] = '090d21f34246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('profile_image_key', sa.String(length=2048), nullable=True))
    op.drop_column('personas', 'profile_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('profile_image_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.drop_column('personas', 'profile_image_key')
    # ### end Alembic commands ###
