"""add applied_phishing_case_id to message table

Revision ID: bbb017b8d7ae
Revises: f66a6473f7f0
Create Date: 2025-06-16 03:46:00.151216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb017b8d7ae'
down_revision: Union[str, None] = 'f66a6473f7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('applied_phishing_case_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_applied_phishing_case_id'), 'messages', ['applied_phishing_case_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'phishing_cases', ['applied_phishing_case_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_applied_phishing_case_id'), table_name='messages')
    op.drop_column('messages', 'applied_phishing_case_id')
    # ### end Alembic commands ###
