"""Increase api_key prefix length

Revision ID: c107e218e07e
Revises: 6c33ae1e739e
Create Date: 2025-06-19 13:48:55.288770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c107e218e07e'
down_revision: Union[str, None] = '6c33ae1e739e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_comment='API 키의 앞 8자리 (식별용)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_comment='API 키의 앞 8자리 (식별용)',
               existing_nullable=False)
    # ### end Alembic commands ###
