"""add kakao to socialproviderenum

Revision ID: db710733b455
Revises: 8fb2f3aa640e
Create Date: 2025-06-18 05:56:08.240110

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'db710733b455'
down_revision: Union[str, None] = '8fb2f3aa640e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE socialproviderenum ADD VALUE IF NOT EXISTS 'kakao'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
