"""add image_key to messages table

Revision ID: dc62490172ff
Revises: 5dd377393bdd
Create Date: 2025-06-18 07:57:07.195978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc62490172ff'
down_revision: Union[str, None] = '5dd377393bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('image_key', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'image_key')
    # ### end Alembic commands ###
