"""revert: remove applied_phishing_case_id from message

Revision ID: df8a7c8b775d
Revises: bbb017b8d7ae
Create Date: 2025-06-16 05:54:32.248768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df8a7c8b775d'
down_revision: Union[str, None] = 'bbb017b8d7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_applied_phishing_case_id'), table_name='messages')
    op.drop_constraint(op.f('messages_applied_phishing_case_id_fkey'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'applied_phishing_case_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('applied_phishing_case_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('messages_applied_phishing_case_id_fkey'), 'messages', 'phishing_cases', ['applied_phishing_case_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_messages_applied_phishing_case_id'), 'messages', ['applied_phishing_case_id'], unique=False)
    # ### end Alembic commands ###
